// User Roles
const USER_ROLES = {
  FARMER: 'FARMER',
  OWNER: 'OWNER',
  ADMIN: 'ADMIN'
};

// Owner Verification Status
const VERIFICATION_STATUS = {
  PENDING_VERIFICATION: 'PENDING_VERIFICATION',
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED'
};

// Booking Status
const BOOKING_STATUS = {
  PENDING: 'PENDING',
  AWAITING_PAYMENT: 'AWAITING_PAYMENT',
  CONFIRMED: 'CONFIRMED',
  IN_PROGRESS: 'IN_PROGRESS',
  AWAITING_OWNER_CONFIRMATION: 'AWAITING_OWNER_CONFIRMATION',
  COMPLETED: 'COMPLETED',
  CANCELLED: 'CANCELLED'
};

// Booking Types
const BOOKING_TYPES = {
  RENTAL: 'RENTAL',
  SERVICE: 'SERVICE'
};

// Pricing Models
const PRICING_MODELS = {
  RENTAL: 'RENTAL',
  SERVICE: 'SERVICE'
};

// Tracking Event Types
const TRACKING_EVENTS = {
  CHECK_IN: 'CHECK_IN',
  USAGE: 'USAGE',
  CHECK_OUT: 'CHECK_OUT'
};

// Meter Reading Types
const METER_READING_TYPES = {
  CHECK_IN: 'CHECK_IN',
  CHECK_OUT: 'CHECK_OUT',
  USAGE: 'USAGE'
};

// Payment Status
const PAYMENT_STATUS = {
  PENDING: 'PENDING',
  SUCCESS: 'SUCCESS',
  FAILED: 'FAILED',
  REFUNDED: 'REFUNDED'
};

// Dispute Types
const DISPUTE_TYPES = {
  LATE_RETURN: 'LATE_RETURN',
  EXTRA_USAGE: 'EXTRA_USAGE',
  BILLING_MISMATCH: 'BILLING_MISMATCH',
  EQUIPMENT_CONDITION: 'EQUIPMENT_CONDITION',
  OTHER: 'OTHER'
};

// Dispute Status
const DISPUTE_STATUS = {
  OPEN: 'OPEN',
  UNDER_REVIEW: 'UNDER_REVIEW',
  REFUND_PENDING: 'REFUND_PENDING',
  RESOLVED: 'RESOLVED',
  REJECTED: 'REJECTED'
};

// Resolution Actions
const RESOLUTION_ACTIONS = {
  REFUND: 'REFUND',
  EXTRA_CHARGE: 'EXTRA_CHARGE',
  WARNING: 'WARNING',
  NO_ACTION: 'NO_ACTION'
};

// Equipment Categories
const EQUIPMENT_CATEGORIES = {
  TRACTOR: 'Tractor',
  HARVESTER: 'Harvester',
  PLOUGH: 'Plough',
  SEEDER: 'Seeder',
  SPRAYER: 'Sprayer',
  THRESHER: 'Thresher',
  CULTIVATOR: 'Cultivator',
  ROTAVATOR: 'Rotavator',
  WATER_PUMP: 'Water Pump',
  TRAILER: 'Trailer',
  OTHER: 'Other'
};

// HTTP Status Codes
const HTTP_STATUS = {
  OK: 200,
  CREATED: 201,
  NO_CONTENT: 204,
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  CONFLICT: 409,
  UNPROCESSABLE_ENTITY: 422,
  INTERNAL_SERVER_ERROR: 500
};

module.exports = {
  USER_ROLES,
  VERIFICATION_STATUS,
  BOOKING_STATUS,
  BOOKING_TYPES,
  PRICING_MODELS,
  TRACKING_EVENTS,
  METER_READING_TYPES,
  PAYMENT_STATUS,
  DISPUTE_TYPES,
  DISPUTE_STATUS,
  RESOLUTION_ACTIONS,
  EQUIPMENT_CATEGORIES,
  HTTP_STATUS
};
